[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.1"
  
[context.production.environment]
  HUGO_ENV = "production"
